meta_product_name: "H2near.me"
meta_title: "H2near.me - Cost effective hydrogen transport"
meta_description: "H2near.me is a platform for exploring hydrogen transport solutions"
meta_image: "cover.png" # should exist in `app/assets/images/`
